### ISSUE TITLE
remove form field

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/angular-movies-perf#67]
![angular_remove-formfield-before](https://user-images.githubusercontent.com/10064416/129638048-4ff2a23b-8ba9-49c1-9896-8a4145c23b9b.png)

**Comment by hoebbelsB** [comment]
![bundle](https://user-images.githubusercontent.com/4904455/129638138-a167b72b-2674-4ba6-a48b-3a035e1b5227.png)
